config/routes.rb
Rails.application.routes.draw do 
  resources :avis
  resources :avinashes
  resources :books
  resources :articles do
    resources :comments
  end
  # get "/articles" , to: "articles#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/home/index"

  # get "/articles/:id", to: "articles#show"
  # Defines the root path route ("/")
  root "articles#index"
end

app/models/avi.rb
class Avi < ApplicationRecord
end

app/controllers/avis_controller.rb
class AvisController < ApplicationController
  before_action :set_avi, only: %i[ show edit update destroy ]

  # GET /avis or /avis.json
  def index
    @avis = Avi.all
  end

  # GET /avis/1 or /avis/1.json
  def show
  end

  # GET /avis/new
  def new
    @avi = Avi.new
  end

  # GET /avis/1/edit
  def edit
  end

  # POST /avis or /avis.json
  def create
    @avi = Avi.new(avi_params)

    respond_to do |format|
      if @avi.save
        format.html { redirect_to avi_url(@avi), notice: "Avi was successfully created." }
        format.json { render :show, status: :created, location: @avi }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @avi.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /avis/1 or /avis/1.json
  def update
    respond_to do |format|
      if @avi.update(avi_params)
        format.html { redirect_to avi_url(@avi), notice: "Avi was successfully updated." }
        format.json { render :show, status: :ok, location: @avi }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @avi.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avis/1 or /avis/1.json
  def destroy
    @avi.destroy

    respond_to do |format|
      format.html { redirect_to avis_url, notice: "Avi was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avi
      @avi = Avi.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def avi_params
      params.require(:avi).permit(:name, :age)
    end
end

app/helpers/avis_helper.rb
module AvisHelper
end

app/views/avis/_avi.html.erb
<div id="<%= dom_id avi %>">
  <p>
    <strong>Name:</strong>
    <%= avi.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= avi.age %>
  </p>

</div>

app/views/avis/_form.html.erb
<%= form_with(model: avi) do |form| %>
  <% if avi.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(avi.errors.count, "error") %> prohibited this avi from being saved:</h2>

      <ul>
        <% avi.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/avis/edit.html.erb
<h1>Editing avi</h1>

<%= render "form", avi: @avi %>

<br>

<div>
  <%= link_to "Show this avi", @avi %> |
  <%= link_to "Back to avis", avis_path %>
</div>

app/views/avis/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Avis</h1>

<div id="avis">
  <% @avis.each do |avi| %>
    <%= render avi %>
    <p>
      <%= link_to "Show this avi", avi %>
    </p>
  <% end %>
</div>

<%= link_to "New avi", new_avi_path %>

app/views/avis/new.html.erb
<h1>New avi</h1>

<%= render "form", avi: @avi %>

<br>

<div>
  <%= link_to "Back to avis", avis_path %>
</div>

app/views/avis/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @avi %>

<div>
  <%= link_to "Edit this avi", edit_avi_path(@avi) %> |
  <%= link_to "Back to avis", avis_path %>

  <%= button_to "Destroy this avi", @avi, method: :delete %>
</div>