config/routes.rb
Rails.application.routes.draw do 
  resources :avis
  resources :avinashes
  resources :books
  resources :articles do
    resources :comments
  end
  # get "/articles" , to: "articles#index"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get "/home/index"

  # get "/articles/:id", to: "articles#show"
  # Defines the root path route ("/")
  root "articles#index"
end

app/models/avinash.rb
class Avinash < ApplicationRecord
end

app/controllers/avinashes_controller.rb
class AvinashesController < ApplicationController
  before_action :set_avinash, only: %i[ show edit update destroy ]

  # GET /avinashes or /avinashes.json
  def index
    @avinashes = Avinash.all
  end

  # GET /avinashes/1 or /avinashes/1.json
  def show
  end

  # GET /avinashes/new
  def new
    @avinash = Avinash.new
  end

  # GET /avinashes/1/edit
  def edit
  end

  # POST /avinashes or /avinashes.json
  def create
    @avinash = Avinash.new(avinash_params)

    respond_to do |format|
      if @avinash.save
        format.html { redirect_to avinash_url(@avinash), notice: "Avinash was successfully created." }
        format.json { render :show, status: :created, location: @avinash }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @avinash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /avinashes/1 or /avinashes/1.json
  def update
    respond_to do |format|
      if @avinash.update(avinash_params)
        format.html { redirect_to avinash_url(@avinash), notice: "Avinash was successfully updated." }
        format.json { render :show, status: :ok, location: @avinash }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @avinash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /avinashes/1 or /avinashes/1.json
  def destroy
    @avinash.destroy

    respond_to do |format|
      format.html { redirect_to avinashes_url, notice: "Avinash was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_avinash
      @avinash = Avinash.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def avinash_params
      params.require(:avinash).permit(:name, :age)
    end
end

app/helpers/avinashes_helper.rb
module AvinashesHelper
end

app/views/avinashes/_avinash.html.erb
<div id="<%= dom_id avinash %>">
  <p>
    <strong>Name:</strong>
    <%= avinash.name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= avinash.age %>
  </p>

</div>

app/views/avinashes/_form.html.erb
<%= form_with(model: avinash) do |form| %>
  <% if avinash.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(avinash.errors.count, "error") %> prohibited this avinash from being saved:</h2>

      <ul>
        <% avinash.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :age, style: "display: block" %>
    <%= form.text_field :age %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/avinashes/edit.html.erb
<h1>Editing avinash</h1>

<%= render "form", avinash: @avinash %>

<br>

<div>
  <%= link_to "Show this avinash", @avinash %> |
  <%= link_to "Back to avinashes", avinashes_path %>
</div>

app/views/avinashes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Avinashes</h1>

<div id="avinashes">
  <% @avinashes.each do |avinash| %>
    <%= render avinash %>
    <p>
      <%= link_to "Show this avinash", avinash %>
    </p>
  <% end %>
</div>

<%= link_to "New avinash", new_avinash_path %>

app/views/avinashes/new.html.erb
<h1>New avinash</h1>

<%= render "form", avinash: @avinash %>

<br>

<div>
  <%= link_to "Back to avinashes", avinashes_path %>
</div>

app/views/avinashes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @avinash %>

<div>
  <%= link_to "Edit this avinash", edit_avinash_path(@avinash) %> |
  <%= link_to "Back to avinashes", avinashes_path %>

  <%= button_to "Destroy this avinash", @avinash, method: :delete %>
</div>